### ISSUE TITLE
Color does not update

### ISSUE THREAD

**Issue by wadehays** [projectweekend/angular-skycons#7]
I have an issue were I need to modify the color of an existing icon. I see that there are $watch functions to see if the icon or size changes, but not one for the color. It doesn't look like the skycons library supports changing the color. I suppose you could instantiate a new instance of Skycons, but that feels very hacky. Do you have any other ideas of how this could be done?

**Comment by projectweekend** [comment]
Thanks for opening the issue. Let me take a closer look at things tomorrow during some downtime and I'll get back with you. I appreciate the feedback!

**Comment by jamesjacobs** [comment]
Any news on this? I seems to be unable to change the colour at all. Heres my code:

```
<skycon icon="currentWeather.forecast.icon" size="currentWeather.forecast.iconSize" color="currentWeather.forecast.color"></skycon>
```

```
$scope.currentWeather = {
                forecast: {
                    icon: data.currently.icon,
                    iconSize: 200,
                    color: "white",
                    temperature: data.currently.apparentTemperature,
                    summary: data.currently.summary,
                }
            };
```

All other options work, icon, size, anaimated etc just not colour. I can update the default in angular-skycons.js but thats not ideal.

Am I missing something?

**Comment by projectweekend** [comment]
@wadehays - just pushed an update that watches the color prop for changes and updates the `skycons` object used in the directive. Let me know if this works for you.

**Comment by projectweekend** [comment]
@jamesjacobs just pushed an update to allow changing colors after the animation has started. Update from bower and let me know. Thanks!
